package io.github.monull.adofai;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

public class ADOFAIMapSettings {
    public int version;
    public String artist;
    public String song;
    public String author;
    public String seperateCountdownTime;
    public String songFileName;
    public int bpm;
    public int volume;
    public int offset;
    public int pitch;
    public String hitSound;
    public int hitSoundVolume;
    public String trackColorType;
    public String trackColor;
    public String secondaryTrackColor;
    public int trackColorAnimDuration;
    public String trackColorPulse;
    public int trackPulseLength;
    public String trackStyle;
    public String trackAnimation;
    public int beatsAhead;
    public String trackDisappearAnimation;
    public int beatsBehind;
    public String backGroundColor;
    public String bgImage;
    public String bgImageColor;
    public int parallaxX;
    public int parallaxY;
    public String bgDisplayMode;
    public String lockRot;
    public String loopBG;
    public int unscaledSize;
    public String relativeTo;
    public int positionX;
    public int positionY;
    public int rotation;
    public int zoom;
    public String bgVideo;
    public String loopVideo;
    public int vidOffset;
    public String floorIconOutlines;
    public String stickToFloors;
    public String planetEase;
    public int planetEaseParts;
    public ADOFAIMapSettings(JSONObject json) {
        version = (int) json.get("version");
        artist = (String) json.get("artist");
        song = (String) json.get("song");
        author = (String) json.get("author");
        seperateCountdownTime = (String) json.get("separateCountdownTime");
        songFileName = (String) json.get("songFilename");
        bpm = (int) json.get("bpm");
        volume = (int) json.get("volume");
        offset = (int) json.get("offset");
        pitch = (int) json.get("pitch");
        hitSound = (String) json.get("hitsound");
        hitSoundVolume = (int) json.get("hitsoundVolume");
        trackColorType = (String) json.get("trackColorType");
        trackColor = (String) json.get("trackColor");
        secondaryTrackColor = (String) json.get("secondaryTrackColor");
        trackColorAnimDuration = (int) json.get("trackColorAnimDuration");
        trackColorPulse = (String) json.get("trackColorPulse");
        trackPulseLength = (int) json.get("trackPulseLength");
        trackStyle = (String) json.get("trackStyle");
        trackAnimation = (String) json.get("trackAnimation");
        beatsAhead = (int) json.get("beatsAhead");
        trackDisappearAnimation = (String) json.get("trackDisappearAnimation");
        beatsBehind = (int) json.get("beatsBehind");
        backGroundColor = (String) json.get("backgroundColor");
        bgImage = (String) json.get("bgImage");
        bgImageColor = (String) json.get("bgImageColor");
        JSONArray parallax = (JSONArray) json.get("parallax");
        parallaxX = (int) parallax.get(0);
        parallaxY = (int) parallax.get(1);
        bgDisplayMode = (String) json.get("bgDisplayMode");
        lockRot = (String) json.get("lockRot");
        loopBG = (String) json.get("loopBG");
        unscaledSize = (int) json.get("unscaledSize");
        relativeTo = (String) json.get("relativeTo");
        JSONArray position = (JSONArray) json.get("position");
        positionX = (int) position.get(0);
        positionY = (int) position.get(1);
        rotation = (int) json.get("rotation");
        zoom = (int) json.get("zoom");
        bgVideo = (String) json.get("bgVideo");
        loopVideo = (String) json.get("loopVideo");
        vidOffset = (int) json.get("vidOffset");
        floorIconOutlines = (String) json.get("floorIconOutlines");
        stickToFloors = (String) json.get("stickToFloors");
        planetEase = (String) json.get("planetEase");
        planetEaseParts = (int) json.get("planetEaseParts");
    }
}
